/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.main.java.teamseven.lasertag;

/**
 *
 * @author Daijon Roberts & Drew Stull
 */
public class EntryTerminal extends javax.swing.JFrame {

    /**
     * Creates new form EntryTerminal
     */
    public EntryTerminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redTeamPanel = new javax.swing.JPanel();
        redTeamLabel = new javax.swing.JLabel();
        redTeamCheckBox0 = new javax.swing.JCheckBox();
        redTeamUserIdTextField0 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField0 = new javax.swing.JFormattedTextField();
        redTeamCheckBox1 = new javax.swing.JCheckBox();
        redTeamCheckBox2 = new javax.swing.JCheckBox();
        redTeamCheckBox3 = new javax.swing.JCheckBox();
        redTeamCheckBox4 = new javax.swing.JCheckBox();
        redTeamCheckBox5 = new javax.swing.JCheckBox();
        redTeamCheckBox6 = new javax.swing.JCheckBox();
        redTeamCheckBox7 = new javax.swing.JCheckBox();
        redTeamCheckBox8 = new javax.swing.JCheckBox();
        redTeamCheckBox9 = new javax.swing.JCheckBox();
        redTeamCheckBox10 = new javax.swing.JCheckBox();
        redTeamCheckBox11 = new javax.swing.JCheckBox();
        redTeamCheckBox12 = new javax.swing.JCheckBox();
        redTeamCheckBox13 = new javax.swing.JCheckBox();
        redTeamCheckBox14 = new javax.swing.JCheckBox();
        redTeamCheckBox15 = new javax.swing.JCheckBox();
        redTeamRow0Label = new javax.swing.JLabel();
        redTeamUserIdTextField1 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField1 = new javax.swing.JFormattedTextField();
        redTeamRow1Label = new javax.swing.JLabel();
        redTeamRow2Label = new javax.swing.JLabel();
        redTeamRow3Label = new javax.swing.JLabel();
        redTeamRow4Label = new javax.swing.JLabel();
        redTeamRow5Label = new javax.swing.JLabel();
        redTeamRow6Label = new javax.swing.JLabel();
        redTeamRow7Label = new javax.swing.JLabel();
        redTeamRow8Label = new javax.swing.JLabel();
        redTeamRow9Label = new javax.swing.JLabel();
        redTeamRow10Label = new javax.swing.JLabel();
        redTeamRow11Label = new javax.swing.JLabel();
        redTeamRow12Label = new javax.swing.JLabel();
        redTeamRow13Label = new javax.swing.JLabel();
        redTeamRow14Label = new javax.swing.JLabel();
        redTeamRow15Label = new javax.swing.JLabel();
        redTeamUserIdTextField2 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField2 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField3 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField3 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField4 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField4 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField5 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField5 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField6 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField6 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField7 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField7 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField8 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField8 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField9 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField9 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField10 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField10 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField11 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField11 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField12 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField12 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField13 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField13 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField14 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField14 = new javax.swing.JFormattedTextField();
        redTeamUserIdTextField15 = new javax.swing.JFormattedTextField();
        redTeamCodeNameTextField15 = new javax.swing.JFormattedTextField();
        greenTeamPanel = new javax.swing.JPanel();
        greenTeamLabel = new javax.swing.JLabel();
        greenTeamCodeNameTextField0 = new javax.swing.JFormattedTextField();
        greenTeamUserIdTextField0 = new javax.swing.JFormattedTextField();
        greenTeamRow0Label = new javax.swing.JLabel();
        greenTeamCheckBox0 = new javax.swing.JCheckBox();
        greenTeamCheckBox1 = new javax.swing.JCheckBox();
        greenTeamRow1Label = new javax.swing.JLabel();
        greenTeamUserIdTextField1 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField1 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox2 = new javax.swing.JCheckBox();
        greenTeamRow2Label = new javax.swing.JLabel();
        greenTeamUserIdTextField2 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField2 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox3 = new javax.swing.JCheckBox();
        greenTeamRow3Label = new javax.swing.JLabel();
        greenTeamUserIdTextField3 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField3 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox4 = new javax.swing.JCheckBox();
        greenTeamRow4Label = new javax.swing.JLabel();
        greenTeamUserIdTextField4 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField4 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox5 = new javax.swing.JCheckBox();
        greenTeamRow5Label = new javax.swing.JLabel();
        greenTeamUserIdTextField5 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField5 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox6 = new javax.swing.JCheckBox();
        greenTeamRow6Label = new javax.swing.JLabel();
        greenTeamUserIdTextField6 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField6 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox7 = new javax.swing.JCheckBox();
        greenTeamRow7Label = new javax.swing.JLabel();
        greenTeamUserIdTextField7 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField7 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox8 = new javax.swing.JCheckBox();
        greenTeamRow8Label = new javax.swing.JLabel();
        greenTeamUserIdTextField8 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField8 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox9 = new javax.swing.JCheckBox();
        greenTeamRow9Label = new javax.swing.JLabel();
        greenTeamUserIdTextField9 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField9 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox10 = new javax.swing.JCheckBox();
        greenTeamRow10Label = new javax.swing.JLabel();
        greenTeamUserIdTextField10 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField10 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox11 = new javax.swing.JCheckBox();
        greenTeamRow11Label = new javax.swing.JLabel();
        greenTeamUserIdTextField11 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField11 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox12 = new javax.swing.JCheckBox();
        greenTeamRow12Label = new javax.swing.JLabel();
        greenTeamUserIdTextField12 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField12 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox13 = new javax.swing.JCheckBox();
        greenTeamRow13Label = new javax.swing.JLabel();
        greenTeamUserIdTextField13 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField13 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox14 = new javax.swing.JCheckBox();
        greenTeamRow14Label = new javax.swing.JLabel();
        greenTeamUserIdTextField14 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField14 = new javax.swing.JFormattedTextField();
        greenTeamCheckBox15 = new javax.swing.JCheckBox();
        greenTeamRow15Label = new javax.swing.JLabel();
        greenTeamUserIdTextField15 = new javax.swing.JFormattedTextField();
        greenTeamCodeNameTextField15 = new javax.swing.JFormattedTextField();
        backgroundPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entry Terminal");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 15, 83));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        redTeamPanel.setBackground(new java.awt.Color(153, 0, 0));

        redTeamLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        redTeamLabel.setForeground(new java.awt.Color(255, 255, 255));
        redTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redTeamLabel.setText("RED TEAM");

        redTeamCheckBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCheckBox0ActionPerformed(evt);
            }
        });

        redTeamUserIdTextField0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamUserIdTextField0ActionPerformed(evt);
            }
        });

        redTeamCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCheckBox1ActionPerformed(evt);
            }
        });

        redTeamCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCheckBox12ActionPerformed(evt);
            }
        });

        redTeamRow0Label.setText("0");

        redTeamRow1Label.setText("1");

        redTeamRow2Label.setText("2");

        redTeamRow3Label.setText("3");

        redTeamRow4Label.setText("4");

        redTeamRow5Label.setText("5");

        redTeamRow6Label.setText("6");

        redTeamRow7Label.setText("7");

        redTeamRow8Label.setText("8");

        redTeamRow9Label.setText("9");

        redTeamRow10Label.setText("10");

        redTeamRow11Label.setText("11");

        redTeamRow12Label.setText("12");

        redTeamRow13Label.setText("13");

        redTeamRow14Label.setText("14");

        redTeamRow15Label.setText("15");

        redTeamCodeNameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCodeNameTextField2ActionPerformed(evt);
            }
        });

        redTeamUserIdTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamUserIdTextField3ActionPerformed(evt);
            }
        });

        redTeamCodeNameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCodeNameTextField3ActionPerformed(evt);
            }
        });

        redTeamUserIdTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamUserIdTextField5ActionPerformed(evt);
            }
        });

        redTeamCodeNameTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamCodeNameTextField5ActionPerformed(evt);
            }
        });

        redTeamUserIdTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redTeamUserIdTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redTeamPanelLayout = new javax.swing.GroupLayout(redTeamPanel);
        redTeamPanel.setLayout(redTeamPanelLayout);
        redTeamPanelLayout.setHorizontalGroup(
            redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redTeamPanelLayout.createSequentialGroup()
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(redTeamPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(redTeamCheckBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redTeamCheckBox0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redTeamPanelLayout.createSequentialGroup()
                                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(redTeamRow10Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(redTeamRow11Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(redTeamPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redTeamUserIdTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redTeamCodeNameTextField11))
                                    .addGroup(redTeamPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(redTeamUserIdTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addGap(157, 157, 157))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, redTeamPanelLayout.createSequentialGroup()
                                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(redTeamPanelLayout.createSequentialGroup()
                                            .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(redTeamRow1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(redTeamRow0Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12)
                                            .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(redTeamUserIdTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                                .addComponent(redTeamUserIdTextField0)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, redTeamPanelLayout.createSequentialGroup()
                                            .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(redTeamRow8Label)
                                                .addComponent(redTeamRow9Label)
                                                .addComponent(redTeamRow7Label)
                                                .addComponent(redTeamRow6Label)
                                                .addComponent(redTeamRow5Label)
                                                .addComponent(redTeamRow4Label)
                                                .addComponent(redTeamRow3Label)
                                                .addComponent(redTeamRow2Label))
                                            .addGap(12, 12, 12)
                                            .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(redTeamUserIdTextField2)
                                                .addComponent(redTeamUserIdTextField3)
                                                .addComponent(redTeamUserIdTextField4)
                                                .addComponent(redTeamUserIdTextField5)
                                                .addComponent(redTeamUserIdTextField6)
                                                .addComponent(redTeamUserIdTextField7)
                                                .addComponent(redTeamUserIdTextField9)
                                                .addComponent(redTeamUserIdTextField8))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(redTeamCodeNameTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(redTeamCodeNameTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(redTeamCodeNameTextField3)
                                        .addComponent(redTeamCodeNameTextField4)
                                        .addComponent(redTeamCodeNameTextField5)
                                        .addComponent(redTeamCodeNameTextField6)
                                        .addComponent(redTeamCodeNameTextField7)
                                        .addComponent(redTeamCodeNameTextField8)
                                        .addComponent(redTeamCodeNameTextField9)
                                        .addComponent(redTeamCodeNameTextField10)
                                        .addComponent(redTeamCodeNameTextField0, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, redTeamPanelLayout.createSequentialGroup()
                                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(redTeamRow15Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(redTeamRow14Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(redTeamPanelLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(redTeamUserIdTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                        .addGroup(redTeamPanelLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(redTeamUserIdTextField15)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(redTeamCodeNameTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                            .addGroup(redTeamPanelLayout.createSequentialGroup()
                                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(redTeamUserIdTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, redTeamPanelLayout.createSequentialGroup()
                                            .addComponent(redTeamRow13Label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(redTeamUserIdTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(redTeamRow12Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(redTeamCodeNameTextField12)
                                    .addComponent(redTeamCodeNameTextField14)
                                    .addComponent(redTeamCodeNameTextField13)))))
                    .addComponent(redTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        redTeamPanelLayout.setVerticalGroup(
            redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redTeamPanelLayout.createSequentialGroup()
                .addComponent(redTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(redTeamCodeNameTextField0)
                    .addComponent(redTeamCheckBox0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redTeamRow0Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redTeamUserIdTextField0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox1)
                    .addComponent(redTeamUserIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamRow1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox2)
                    .addComponent(redTeamRow2Label)
                    .addComponent(redTeamUserIdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox3)
                    .addComponent(redTeamRow3Label)
                    .addComponent(redTeamUserIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox4)
                    .addComponent(redTeamRow4Label)
                    .addComponent(redTeamUserIdTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox5)
                    .addComponent(redTeamRow5Label)
                    .addComponent(redTeamUserIdTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox6)
                    .addComponent(redTeamRow6Label)
                    .addComponent(redTeamUserIdTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox7)
                    .addComponent(redTeamRow7Label)
                    .addComponent(redTeamUserIdTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox8)
                    .addComponent(redTeamRow8Label)
                    .addComponent(redTeamUserIdTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox9)
                    .addComponent(redTeamRow9Label)
                    .addComponent(redTeamUserIdTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox10)
                    .addComponent(redTeamRow10Label)
                    .addComponent(redTeamUserIdTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(redTeamCheckBox11)
                        .addComponent(redTeamRow11Label)
                        .addComponent(redTeamUserIdTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(redTeamCodeNameTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox12)
                    .addComponent(redTeamRow12Label)
                    .addComponent(redTeamUserIdTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox13)
                    .addComponent(redTeamRow13Label)
                    .addComponent(redTeamUserIdTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox14)
                    .addComponent(redTeamRow14Label)
                    .addComponent(redTeamUserIdTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(redTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redTeamCheckBox15)
                    .addComponent(redTeamRow15Label)
                    .addComponent(redTeamUserIdTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redTeamCodeNameTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        greenTeamPanel.setBackground(new java.awt.Color(0, 153, 0));
        greenTeamPanel.setForeground(new java.awt.Color(51, 255, 0));

        greenTeamLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        greenTeamLabel.setForeground(new java.awt.Color(255, 255, 255));
        greenTeamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greenTeamLabel.setText("GREEN TEAM");

        greenTeamRow0Label.setText("0");

        greenTeamCheckBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenTeamCheckBox0ActionPerformed(evt);
            }
        });

        greenTeamCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenTeamCheckBox1ActionPerformed(evt);
            }
        });

        greenTeamRow1Label.setText("1");

        greenTeamRow2Label.setText("2");

        greenTeamRow3Label.setText("3");

        greenTeamCheckBox4.setText("jCheckBox1");

        greenTeamRow4Label.setText("4");

        greenTeamRow5Label.setText("5");

        greenTeamRow6Label.setText("6");

        greenTeamRow7Label.setText("7");

        greenTeamRow8Label.setText("8");

        greenTeamRow9Label.setText("9");

        greenTeamRow10Label.setText("10");

        greenTeamRow11Label.setText("11");

        greenTeamCheckBox12.setText("jCheckBox1");

        greenTeamRow12Label.setText("12");

        greenTeamCheckBox13.setText("jCheckBox1");

        greenTeamRow13Label.setText("13");

        greenTeamCheckBox14.setText("jCheckBox1");
        greenTeamCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenTeamCheckBox14ActionPerformed(evt);
            }
        });

        greenTeamRow14Label.setText("14");

        greenTeamCheckBox15.setText("jCheckBox1");

        greenTeamRow15Label.setText("15");

        javax.swing.GroupLayout greenTeamPanelLayout = new javax.swing.GroupLayout(greenTeamPanel);
        greenTeamPanel.setLayout(greenTeamPanelLayout);
        greenTeamPanelLayout.setHorizontalGroup(
            greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenTeamPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow0Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamUserIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow2Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow3Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow4Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow5Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow6Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamUserIdTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow8Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamRow9Label)
                        .addGap(18, 18, 18)
                        .addComponent(greenTeamUserIdTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(greenTeamRow10Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamUserIdTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(greenTeamRow11Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamUserIdTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamRow12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamUserIdTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                        .addComponent(greenTeamCheckBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTeamRow13Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamUserIdTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greenTeamCodeNameTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(greenTeamPanelLayout.createSequentialGroup()
                        .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(greenTeamCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(greenTeamCheckBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(greenTeamRow14Label, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(greenTeamRow15Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                                .addComponent(greenTeamUserIdTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greenTeamCodeNameTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenTeamPanelLayout.createSequentialGroup()
                                .addComponent(greenTeamUserIdTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greenTeamCodeNameTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(greenTeamPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(greenTeamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        greenTeamPanelLayout.setVerticalGroup(
            greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenTeamPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField0)
                    .addComponent(greenTeamUserIdTextField0)
                    .addComponent(greenTeamRow0Label)
                    .addComponent(greenTeamCheckBox0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField1)
                    .addComponent(greenTeamUserIdTextField1)
                    .addComponent(greenTeamRow1Label)
                    .addComponent(greenTeamCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField2)
                    .addComponent(greenTeamUserIdTextField2)
                    .addComponent(greenTeamRow2Label)
                    .addComponent(greenTeamCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField3)
                    .addComponent(greenTeamUserIdTextField3)
                    .addComponent(greenTeamRow3Label)
                    .addComponent(greenTeamCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField4)
                    .addComponent(greenTeamUserIdTextField4)
                    .addComponent(greenTeamRow4Label)
                    .addComponent(greenTeamCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField5)
                    .addComponent(greenTeamUserIdTextField5)
                    .addComponent(greenTeamRow5Label)
                    .addComponent(greenTeamCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField6)
                    .addComponent(greenTeamUserIdTextField6)
                    .addComponent(greenTeamRow6Label)
                    .addComponent(greenTeamCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField7)
                    .addComponent(greenTeamUserIdTextField7)
                    .addComponent(greenTeamRow7Label)
                    .addComponent(greenTeamCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField8)
                    .addComponent(greenTeamUserIdTextField8)
                    .addComponent(greenTeamRow8Label)
                    .addComponent(greenTeamCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField9)
                    .addComponent(greenTeamUserIdTextField9)
                    .addComponent(greenTeamRow9Label)
                    .addComponent(greenTeamCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField10)
                    .addComponent(greenTeamUserIdTextField10)
                    .addComponent(greenTeamRow10Label)
                    .addComponent(greenTeamCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField11)
                    .addComponent(greenTeamUserIdTextField11)
                    .addComponent(greenTeamRow11Label)
                    .addComponent(greenTeamCheckBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField12)
                    .addComponent(greenTeamUserIdTextField12)
                    .addComponent(greenTeamRow12Label)
                    .addComponent(greenTeamCheckBox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField13)
                    .addComponent(greenTeamUserIdTextField13)
                    .addComponent(greenTeamRow13Label)
                    .addComponent(greenTeamCheckBox13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField14)
                    .addComponent(greenTeamUserIdTextField14)
                    .addComponent(greenTeamRow14Label)
                    .addComponent(greenTeamCheckBox14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenTeamCodeNameTextField15)
                    .addComponent(greenTeamUserIdTextField15)
                    .addComponent(greenTeamRow15Label)
                    .addComponent(greenTeamCheckBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(greenTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(greenTeamPanelLayout.createSequentialGroup()
                    .addComponent(greenTeamLabel)
                    .addGap(0, 476, Short.MAX_VALUE)))
        );

        backgroundPanel.setBackground(new java.awt.Color(0, 0, 0));

        startButton.setBackground(new java.awt.Color(0, 255, 0));
        startButton.setText("START");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        titleLabel.setBackground(new java.awt.Color(0, 0, 0));
        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(153, 0, 153));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("EDIT CURRENT GAME");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(redTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(386, 386, 386)
                    .addComponent(greenTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(redTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(greenTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redTeamUserIdTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamUserIdTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamUserIdTextField7ActionPerformed

    private void redTeamCodeNameTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCodeNameTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCodeNameTextField5ActionPerformed

    private void redTeamUserIdTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamUserIdTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamUserIdTextField5ActionPerformed

    private void redTeamCodeNameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCodeNameTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCodeNameTextField3ActionPerformed

    private void redTeamUserIdTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamUserIdTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamUserIdTextField3ActionPerformed

    private void redTeamCodeNameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCodeNameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCodeNameTextField2ActionPerformed

    private void redTeamUserIdTextField0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamUserIdTextField0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamUserIdTextField0ActionPerformed

    private void redTeamCheckBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCheckBox0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCheckBox0ActionPerformed

    private void redTeamCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCheckBox1ActionPerformed

    private void greenTeamCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenTeamCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenTeamCheckBox1ActionPerformed

    private void redTeamCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redTeamCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redTeamCheckBox12ActionPerformed

    private void greenTeamCheckBox0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenTeamCheckBox0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenTeamCheckBox0ActionPerformed

    private void greenTeamCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenTeamCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenTeamCheckBox14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EntryTerminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JCheckBox greenTeamCheckBox0;
    private javax.swing.JCheckBox greenTeamCheckBox1;
    private javax.swing.JCheckBox greenTeamCheckBox10;
    private javax.swing.JCheckBox greenTeamCheckBox11;
    private javax.swing.JCheckBox greenTeamCheckBox12;
    private javax.swing.JCheckBox greenTeamCheckBox13;
    private javax.swing.JCheckBox greenTeamCheckBox14;
    private javax.swing.JCheckBox greenTeamCheckBox15;
    private javax.swing.JCheckBox greenTeamCheckBox2;
    private javax.swing.JCheckBox greenTeamCheckBox3;
    private javax.swing.JCheckBox greenTeamCheckBox4;
    private javax.swing.JCheckBox greenTeamCheckBox5;
    private javax.swing.JCheckBox greenTeamCheckBox6;
    private javax.swing.JCheckBox greenTeamCheckBox7;
    private javax.swing.JCheckBox greenTeamCheckBox8;
    private javax.swing.JCheckBox greenTeamCheckBox9;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField0;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField1;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField10;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField11;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField12;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField13;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField14;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField15;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField2;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField3;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField4;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField5;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField6;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField7;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField8;
    private javax.swing.JFormattedTextField greenTeamCodeNameTextField9;
    private javax.swing.JLabel greenTeamLabel;
    private javax.swing.JPanel greenTeamPanel;
    private javax.swing.JLabel greenTeamRow0Label;
    private javax.swing.JLabel greenTeamRow10Label;
    private javax.swing.JLabel greenTeamRow11Label;
    private javax.swing.JLabel greenTeamRow12Label;
    private javax.swing.JLabel greenTeamRow13Label;
    private javax.swing.JLabel greenTeamRow14Label;
    private javax.swing.JLabel greenTeamRow15Label;
    private javax.swing.JLabel greenTeamRow1Label;
    private javax.swing.JLabel greenTeamRow2Label;
    private javax.swing.JLabel greenTeamRow3Label;
    private javax.swing.JLabel greenTeamRow4Label;
    private javax.swing.JLabel greenTeamRow5Label;
    private javax.swing.JLabel greenTeamRow6Label;
    private javax.swing.JLabel greenTeamRow7Label;
    private javax.swing.JLabel greenTeamRow8Label;
    private javax.swing.JLabel greenTeamRow9Label;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField0;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField1;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField10;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField11;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField12;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField13;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField14;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField15;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField2;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField3;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField4;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField5;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField6;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField7;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField8;
    private javax.swing.JFormattedTextField greenTeamUserIdTextField9;
    private javax.swing.JCheckBox redTeamCheckBox0;
    private javax.swing.JCheckBox redTeamCheckBox1;
    private javax.swing.JCheckBox redTeamCheckBox10;
    private javax.swing.JCheckBox redTeamCheckBox11;
    private javax.swing.JCheckBox redTeamCheckBox12;
    private javax.swing.JCheckBox redTeamCheckBox13;
    private javax.swing.JCheckBox redTeamCheckBox14;
    private javax.swing.JCheckBox redTeamCheckBox15;
    private javax.swing.JCheckBox redTeamCheckBox2;
    private javax.swing.JCheckBox redTeamCheckBox3;
    private javax.swing.JCheckBox redTeamCheckBox4;
    private javax.swing.JCheckBox redTeamCheckBox5;
    private javax.swing.JCheckBox redTeamCheckBox6;
    private javax.swing.JCheckBox redTeamCheckBox7;
    private javax.swing.JCheckBox redTeamCheckBox8;
    private javax.swing.JCheckBox redTeamCheckBox9;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField0;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField1;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField10;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField11;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField12;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField13;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField14;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField15;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField2;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField3;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField4;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField5;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField6;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField7;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField8;
    private javax.swing.JFormattedTextField redTeamCodeNameTextField9;
    private javax.swing.JLabel redTeamLabel;
    private javax.swing.JPanel redTeamPanel;
    private javax.swing.JLabel redTeamRow0Label;
    private javax.swing.JLabel redTeamRow10Label;
    private javax.swing.JLabel redTeamRow11Label;
    private javax.swing.JLabel redTeamRow12Label;
    private javax.swing.JLabel redTeamRow13Label;
    private javax.swing.JLabel redTeamRow14Label;
    private javax.swing.JLabel redTeamRow15Label;
    private javax.swing.JLabel redTeamRow1Label;
    private javax.swing.JLabel redTeamRow2Label;
    private javax.swing.JLabel redTeamRow3Label;
    private javax.swing.JLabel redTeamRow4Label;
    private javax.swing.JLabel redTeamRow5Label;
    private javax.swing.JLabel redTeamRow6Label;
    private javax.swing.JLabel redTeamRow7Label;
    private javax.swing.JLabel redTeamRow8Label;
    private javax.swing.JLabel redTeamRow9Label;
    private javax.swing.JFormattedTextField redTeamUserIdTextField0;
    private javax.swing.JFormattedTextField redTeamUserIdTextField1;
    private javax.swing.JFormattedTextField redTeamUserIdTextField10;
    private javax.swing.JFormattedTextField redTeamUserIdTextField11;
    private javax.swing.JFormattedTextField redTeamUserIdTextField12;
    private javax.swing.JFormattedTextField redTeamUserIdTextField13;
    private javax.swing.JFormattedTextField redTeamUserIdTextField14;
    private javax.swing.JFormattedTextField redTeamUserIdTextField15;
    private javax.swing.JFormattedTextField redTeamUserIdTextField2;
    private javax.swing.JFormattedTextField redTeamUserIdTextField3;
    private javax.swing.JFormattedTextField redTeamUserIdTextField4;
    private javax.swing.JFormattedTextField redTeamUserIdTextField5;
    private javax.swing.JFormattedTextField redTeamUserIdTextField6;
    private javax.swing.JFormattedTextField redTeamUserIdTextField7;
    private javax.swing.JFormattedTextField redTeamUserIdTextField8;
    private javax.swing.JFormattedTextField redTeamUserIdTextField9;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
